name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["SonarQube-Scan and Build JAR"]
    types:
      - completed
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest
    if: github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.workflow, 'SonarQube-Scan and Build JAR')

    steps:
      - name: Debug Info
        run: |
          echo "Event: ${{ toJson(github.event) }}"
          echo "Workflow Run Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow Run Workflow: ${{ github.event.workflow_run.workflow }}"
        # Rest of your steps...
      
      - name: Checkout
        uses: actions/checkout@v2

      # Rest of your steps...
